version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/.logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www
    networks:
      - lemp

  php:
    build:
      context: './docker/php'
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php.ini-development
    networks:
      - lemp

  postgres:
    image: postgres:14.1
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mvc
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lemp

  composer:
    image: composer:2.2.4
    container_name: composer
    volumes:
      - ./src/:/app
    networks:
      - lemp

volumes:
  db_data: {}

networks:
  lemp:
    driver: bridge
